export const dummyDataNews = [
    {id: 0, date_created: '03/28/2023', title: 'Tin tức 1', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung đây là nội dung đây là nội dung đây đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung'}, 
    {id: 1, date_created: '03/28/2023', title: 'Tin tức 2', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 2, date_created: '03/28/2023', title: 'Tin tức 3', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 3, date_created: '03/28/2023', title: 'Tin tức 4', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 4, date_created: '03/28/2023', title: 'Tin tức 5', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 5, date_created: '03/28/2023', title: 'Tin tức 6', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 6, date_created: '03/28/2023', title: 'Tin tức 7', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 7, date_created: '03/28/2023', title: 'Tin tức 8', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 8, date_created: '03/28/2023', title: 'Tin tức 1', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung đây là nội dung đây là nội dung đây đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung'}, 
    {id: 9, date_created: '03/28/2023', title: 'Tin tức 2', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 10, date_created: '03/28/2023', title: 'Tin tức 3', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 11, date_created: '03/28/2023', title: 'Tin tức 4', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 12, date_created: '03/28/2023', title: 'Tin tức 5', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 13, date_created: '03/28/2023', title: 'Tin tức 6', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 14, date_created: '03/28/2023', title: 'Tin tức 7', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 15, date_created: '03/28/2023', title: 'Tin tức 8', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 16, date_created: '03/28/2023', title: 'Tin tức 1', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung đây là nội dung đây là nội dung đây đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung đây là nội dung đây là nội dungđây là nội dungđây là nội dungđây là nội dungđây là nội dung đây là nội dung đây là nội dung'}, 
    {id: 17, date_created: '03/28/2023', title: 'Tin tức 2', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 18, date_created: '03/28/2023', title: 'Tin tức 3', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 19, date_created: '03/28/2023', title: 'Tin tức 4', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 20, date_created: '03/28/2023', title: 'Tin tức 5', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 21, date_created: '03/28/2023', title: 'Tin tức 6', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 22, date_created: '03/28/2023', title: 'Tin tức 7', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
    {id: 23, date_created: '03/28/2023', title: 'Tin tức 8', image: 'https://thumbs.dreamstime.com/b/orange-sky-over-sea-sunset-coloring-clouds-bright-light-51802926.jpg', content: 'đây là nội dung'},
];

export const dummyDataUsers = [
    {id: 0, name: 'Admin 1', gmail: 'admin@gmail.com', password: '123456', status: 'Hoạt động', isAdmin: true},
    {id: 1, name: 'User 2', gmail: 'user2@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 2, name: 'User 3', gmail: 'user3@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 3, name: 'User 4', gmail: 'user4@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 4, name: 'User 5', gmail: 'user5@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 5, name: 'User 6', gmail: 'user6@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 6, name: 'User 7', gmail: 'user7@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 7, name: 'User 8', gmail: 'user8@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 8, name: 'User 9', gmail: 'user9@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 9, name: 'User 10', gmail: 'user10@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 10, name: 'User 11', gmail: 'user11@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 11, name: 'User 12', gmail: 'user12@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 12, name: 'User 13', gmail: 'user13@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 13, name: 'User 14', gmail: 'user14@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 14, name: 'User 15', gmail: 'user15@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 15, name: 'User 16', gmail: 'user16@gmail.com', password: '123456', status: 'Hoạt động'},
    {id: 16, name: 'User 17', gmail: 'user17@gmail.com', password: '123456', status: 'Hoạt động'},
]